language: php
php:
  - 5.5
  - 5.6
  - 7.0
branches:
  only:
    master

before_script:
  - composer require phpunit/phpunit

script: phpunit --exclude-group FITS --bootstrap tests/bootstrap.php tests